### PR TITLE
Setup AfterBuildSteps parameter on CI build

### PR DESCRIPTION
**Pull request by christophebdelaware**
Add custom CI steps after the build action

### CODE REVIEW

**Comment by WimVergouwe** [comment]
> Add custom CI steps after the build action
Could you explain the scenario, why do you need this?

**Comment by WimVergouwe** [comment]
That's indeed a common scenario.
We typically do these kinds of things by extending the msbuild publish and including additional resources (see the Dlw.Platina.Build nuget package).
The template will include all publish output automatically in the pipeline artifacts.
Is this approach an option for you?
@dejonghee, wdyt?

**Comment by WimVergouwe** [comment]
Example of including entity framework migration script in pipeline output
```
  <Target Name="PublishEFMigrationScript"
          AfterTargets="Publish"
          Condition=" '$(EfPublishable)' == 'true' ">

    <Message Text="Publishing EF migrations script for $(ProjectName)..." Importance="high" />
    
    <Exec Command="dotnet ef migrations script --idempotent --no-build --configuration $(ConfigurationName) --output $(PublishDir)\$(ProjectName).sql"  />

    <Message Text="Publishing EF migrations script for $(ProjectName) done." Importance="high" />
  </Target>
```

**Comment by christophebdelaware** [comment]
> 

Because the dynamic step parameter was not provided we provided a similar setup as workaround. The only difference is that we let the script run on release build and put the outcome directly to artifacts (when available).

Like the existing `BeforeTestsSteps` / `AfterTestsSteps` parameters, the `AfterBuildSteps` can also be an improvement for future scenarios. Thinking of steps that need to be done after a build (scripts/extra tasks) that can't be covered in an msbuild.

**Comment by WimVergouwe** [comment]
It could id be an improvement for future scenarios, but then we should also add before and after steps for pack, publish, push, ...
So I suggest we leave it alone for now. 
If you would like to follow up, it might be better to have a teams call, feel free to reach out.

**Pull request closed without merging**
